<?php
$lang["bar_verwaltung"]="Seitenbereiche";
$lang["bar_neu"]="Neuen Seitenbereich erstellen";
$lang["bar_bearbeiten"]="Seitenbereich bearbeiten";
$lang["bar_name"]="Name";
$lang["bar_typ"]="Typ des Seitenbereichs";
$lang["bar_eintrag"]="Eintrag";
$lang["bar_speichern"]="Bereich speichern";
$lang["bar_update_fehlgeschlagen"]="Fehler: Die &Auml;nderungen konnten nicht &uuml;bernommen werden";
$lang["bar_update_erfolgreich"]="Bereich erfolgreich ge&auml;ndert";
$lang["bar_insert_fehlgeschlagen"]="Fehler: Bereich konnte nicht angelegt werden";
$lang["bar_insert_erfolgreich"]="Bereich erfolgreich eingef&uuml;gt";
$lang["bar_delete_fehlgeschlagen"]="Fehler: Bereich konnte nicht gel&ouml;scht werden";
$lang["bar_delete_erfolgreich"]="Bereich erfolgreich gel&ouml;scht";
$lang["bar_eintrag_neu"]="Neuen Eintrag erstellen";
$lang["bar_eintrag_typ"]="Typ des Eintrags";
$lang["bar_eintrag_name"]="Name des Eintrags";
$lang["bar_eintrag_bearbeiten"]="Eintrag bearbeiten";
$lang["bar_eintrag_update_fehlgeschlagen"]="Fehler: &Auml;nderungen konnten nicht &uuml;bernommen werden";
$lang["bar_eintrag_update_erfolgreich"]="Eintrag erfolgreich ge&auml;ndert";
$lang["bar_eintrag_insert_fehlgeschlagen"]="Fehler: Eintrag konnte nicht angelegt werden";
$lang["bar_eintrag_insert_erfolgreich"]="Eintrag  erfolgreich angelegt";
$lang["bar_eintrag_delete_fehlgeschlagen"]="Fehler: Eintrag konnte nicht gel&ouml;scht werden";
$lang["bar_eintrag_delete_erfolgreich"]="Eintrag erfolgreich gel&ouml;scht";
$lang["bar_eintrag_move_fehlgeschlagen"]="Fehler: Eintrag konnte nicht verschoben werden";
$lang["bar_eintrag_move_erfolgreich"]="Eintrag erfolgreich verschoben";
$lang["bar_eintrag_am_anfang"]="am Anfang";
$lang["bar_eintrag_am_ende"]="am Ende";

?>