<?php
$lang["admin_redaktionsbereich"]="ACME :: administration";
$lang["admin_artikel"]="article";
$lang["admin_page"]="pages";
$lang["admin_navigation"]="navigation";
$lang["admin_bilder"]="images";
$lang["admin_blog"]="blogs";
$lang["admin_glossar"]="glossary";
$lang["admin_templates"]="templates";
$lang["admin_styles"]="stylesheets";
$lang["admin_user"]="user administration";
$lang["admin_blocks"]="blocks";
$lang["admin_groups"]="user groups";
$lang["admin_profile"]="page profiles";
$lang["admin_termine"]="dates";
$lang["admin_autoren"]="authors";
$lang["admin_urls"]="links";
$lang["admin_messages"]="messages";
$lang["admin_downloads"]="downloads";
$lang["admin_bar"]="page bars";
$lang["admin_news"]="news";
$lang["admin_sitemap"]="sitemap";
$lang["admin_gaestebuch"]="guestbooks";
$lang["admin_hilfe"]="help-wiki";
$lang["admin_content"]="content";
$lang["admin_layout"]="structure";
$lang["admin_admin"]="options";

$lang["admin_logout"]="logout";
?>