<?php
// auth
$lang["authorisierung"]="Autorisierung erforderlich";
$lang["authorisierung_fehler"]="error: authorization failure";
$lang["authorisierung_unbekannt"]="username and password don't match";
$lang["authorisierung_gesperrt"]="user disabled, please contact you admin";
$lang["authorisierung_neu_anmelden"]="login";
$lang["authorisierung_username"]="Benutzername";
$lang["authorisierung_passwort"]="Passwort";
?>