<?php
$lang["autoren_management"]="authors";
$lang["autoren_neu_anlegen"]="create new author";
$lang["autoren_name"]="Name";
$lang["autoren_gruppe"]="Gruppe";
$lang["autoren_aktiv"]="aktiv";
$lang["autoren_self"]="-----";
$lang["autoren_pass"]="Passwort";
$lang["autoren_nachname"]="surname";
$lang["autoren_vorname"]="given name";
$lang["autoren_email"]="email";
$lang["autoren_img"]="image";
$lang["autoren_url"]="URL";
$lang["autoren_text"]="text";
$lang["autoren_bearbeiten"]="edit author";
$lang["autoren_loeschen"]="delete author";
$lang["autoren_speichern"]="save";
$lang["autoren_insert_erfolgreich"]="author created successfully"; // ????
$lang["autoren_insert_fehlgeschlagen"]="error: author could not be created"; // ???
$lang["autoren_update_erfolgreich"]="author updated successfully"; // ????
$lang["autoren_update_fehlgeschlagen"]="error: author could not be updated"; // ???
$lang["autoren_delete_erfolgreich"]="author deleted successfully"; // ????
$lang["autoren_delete_fehlgeschlagen"]="error: author could not be deleted"; // ???
?>