<?php
$lang["autoren_management"]="Autoren";
$lang["autoren_neu_anlegen"]="Neuen Autor anlegen";
$lang["autoren_name"]="Name";
$lang["autoren_gruppe"]="Gruppe";
$lang["autoren_aktiv"]="aktiv";
$lang["autoren_self"]="-----";
$lang["autoren_pass"]="Passwort";
$lang["autoren_nachname"]="Nachname";
$lang["autoren_vorname"]="Vorname";
$lang["autoren_email"]="email";
$lang["autoren_img"]="Bild";
$lang["autoren_url"]="URL";
$lang["autoren_text"]="Text";
$lang["autoren_bearbeiten"]="Autor bearbeiten";
$lang["autoren_loeschen"]="Autor l&ouml;schen";
$lang["autoren_speichern"]="speichern";
$lang["autoren_insert_erfolgreich"]="Autor erfolgreich eingef&uuml;gt"; // ????
$lang["autoren_insert_fehlgeschlagen"]="Fehler: Autor konnte nicht eingef&uuml;gt werden"; // ???
$lang["autoren_update_erfolgreich"]="Autor erfolgreich ge&auml;ndert"; // ????
$lang["autoren_update_fehlgeschlagen"]="Fehler: Autoren konnte nicht ge&auml;ndert werden"; // ???
$lang["autoren_delete_erfolgreich"]="Autor erfolgreich gel&ouml;scht"; // ????
$lang["autoren_delete_fehlgeschlagen"]="Fehler: Autor konnte nicht gel&ouml;scht werden"; // ???
?>