<?php
$lang["bar_verwaltung"]="page bars";
$lang["bar_neu"]="create new page bar";
$lang["bar_bearbeiten"]="edit page bar";
$lang["bar_name"]="bar name";
$lang["bar_typ"]="bar type";
$lang["bar_eintrag"]="entry";
$lang["bar_speichern"]="save";
$lang["bar_update_fehlgeschlagen"]="error: bar could not be updated";
$lang["bar_update_erfolgreich"]="bar updated successfully";
$lang["bar_insert_fehlgeschlagen"]="error: bar could not be created";
$lang["bar_insert_erfolgreich"]="bar created successfully";
$lang["bar_delete_fehlgeschlagen"]="error: bar could not be deleted";
$lang["bar_delete_erfolgreich"]="bar deleted successfully";
$lang["bar_eintrag_neu"]="create new entry";
$lang["bar_eintrag_typ"]="entry type";
$lang["bar_eintrag_name"]="entry name";
$lang["bar_eintrag_bearbeiten"]="edit entry";
$lang["bar_eintrag_update_fehlgeschlagen"]="error: entry could not be updated";
$lang["bar_eintrag_update_erfolgreich"]="entry updated successfully";
$lang["bar_eintrag_insert_fehlgeschlagen"]="error: entry could not be created";
$lang["bar_eintrag_insert_erfolgreich"]="entry created successfully";
$lang["bar_eintrag_delete_fehlgeschlagen"]="error: entry could not be deleted";
$lang["bar_eintrag_delete_erfolgreich"]="entry deleted successfully";
$lang["bar_eintrag_move_fehlgeschlagen"]="error: entry could not be moved";
$lang["bar_eintrag_move_erfolgreich"]="entry moved successfully";
$lang["bar_eintrag_am_anfang"]="at the first position";
$lang["bar_eintrag_am_ende"]="at the last position";

?>