<?php
$lang["blocks_verwaltung"]="Blockverwaltung";
$lang["blocks_speichern"]="speichern";
$lang["blocks_neu"]="Neuen Block anlegen";
$lang["blocks_bearbeiten"]="Block bearbeiten";
$lang["blocks_id"]="ID";
$lang["blocks_name"]="Blockname";
$lang["blocks_typ"]="Blocktyp";
$lang["blocks_inhalt"]="Inhalt";
$lang["blocks_image"]="Bild";
$lang["blocks_speichern"]="speichern";
$lang["blocks_insert_fehlerhaft"]="Fehler: Block konnte nicht eingef&uuml;gt werden";
$lang["blocks_insert_erfolgreich"]="Block einf&uuml;gen erfolgreich";
$lang["blocks_update_fehlerhaft"]="Fehler: Block bearbeiten fehlgeschlagen";
$lang["blocks_update_erfolgreich"]="Block bearbeiten erfolgreich";
$lang["blocks_delete_fehlerhaft"]="Fehler: Block l&ouml;schen fehlgeschlagen";
$lang["blocks_delete_erfolgreich"]="Block l&ouml;schen erfolgreich";
?>