<?php
$lang["blocks_verwaltung"]="blocks";
$lang["blocks_speichern"]="save";
$lang["blocks_neu"]="create new block";
$lang["blocks_bearbeiten"]="edit block";
$lang["blocks_id"]="ID";
$lang["blocks_name"]="block name";
$lang["blocks_typ"]="block type";
$lang["blocks_inhalt"]="content";
$lang["blocks_image"]="image";
$lang["blocks_speichern"]="save";
$lang["blocks_insert_fehlerhaft"]="error: block could not be created";
$lang["blocks_insert_erfolgreich"]="block created successfully";
$lang["blocks_update_fehlerhaft"]="error: block could not be edited";
$lang["blocks_update_erfolgreich"]="block edited successfully";
$lang["blocks_delete_fehlerhaft"]="error: block could not be deleted";
$lang["blocks_delete_erfolgreich"]="block deleted successfully";
?>