<?php
$lang["gaestebuch_verwaltung"]="guestbooks ";
$lang["gaestebuch_name"]="name";
$lang["gaestebuch_anlegen"]="create guestbook";
$lang["gaestebuch_bearbeiten"]="update guestbook";
$lang["gaestebuch_logo_klein"]="small icon (nav akt)";
$lang["gaestebuch_logo_klein_inactive"]="small icon (nav inakt)";
$lang["gaestebuch_logo_gross"]="large icon";
$lang["gaestebuch_speichern"]="save";
$lang["gaestebuch_bar_top"]="top bar";
$lang["gaestebuch_bar_right"]="right bar";
$lang["gaestebuch_bar_left"]="left bar";
$lang["gaestebuch_bar_bottom"]="bottom bar";
$lang["gaestebuch_insert_erfolgreich"]="guestbook created successfully"; // ????
$lang["gaestebuch_insert_fehlgeschlagen"]="error: guestbook could not be created"; // ???
$lang["gaestebuch_update_erfolgreich"]="guestbook updated successfully"; // ????
$lang["gaestebuch_update_fehlgeschlagen"]="error: guestbook could not be updated"; // ???
$lang["gaestebuch_delete_erfolgreich"]="guestbook deleted successfully"; // ????
$lang["gaestebuch_delete_fehlgeschlagen"]="guestbook: sitemap could not be deleted"; // ???
?>