<?php
$lang["gaestebuch_verwaltung"]="G&auml;steb&uuml;cher";
$lang["gaestebuch_name"]="name";
$lang["gaestebuch_anlegen"]="G&auml;stebuch erstellen";
$lang["gaestebuch_bearbeiten"]="G&auml;stebuch bearbeiten";
$lang["gaestebuch_logo_klein"]="small icon (nav akt)";
$lang["gaestebuch_logo_klein_inactive"]="small icon (nav inakt)";
$lang["gaestebuch_logo_gross"]="large icon";
$lang["gaestebuch_speichern"]="save";
$lang["gaestebuch_bar_top"]="Seitenbereich oben";
$lang["gaestebuch_bar_right"]="Seitenbereich rechts";
$lang["gaestebuch_bar_left"]="Seitenbereich links";
$lang["gaestebuch_bar_bottom"]="Seitenbereich unten";
$lang["gaestebuch_insert_erfolgreich"]="G&auml;stebuch created successfully"; // ????
$lang["gaestebuch_insert_fehlgeschlagen"]="error: G&auml;stebuch could not be created"; // ???
$lang["gaestebuch_update_erfolgreich"]="G&auml;stebuch updated successfully"; // ????
$lang["gaestebuch_update_fehlgeschlagen"]="error: G&auml;stebuch could not be updated"; // ???
$lang["gaestebuch_delete_erfolgreich"]="G&auml;stebuch deleted successfully"; // ????
$lang["gaestebuch_delete_fehlgeschlagen"]="G&auml;stebuch: sitemap could not be deleted"; // ???
?>