<?php
$lang["glossar_verwaltung"]="glossary";
$lang["glossar_neu"]="create new entry";
$lang["glossar_titel"]="title";
$lang["glossar_text"]="text";
$lang["glossar_bild"]="image";
$lang["glossar_tpl"]="template";
$lang["glossar_anlegen"]="create new entry";
$lang["glossar_bearbeiten"]="edit entry";
$lang["glossar_speichern"]="save";
$lang["glossar_counter"]="counter";
$lang["glossar_loeschen"]="delete entry";
$lang["glossar_notfound"]="error: entry not found";
$lang["glossar_insert_erfolgreich"]="entry created successfully"; // ????
$lang["glossar_insert_fehlgeschlagen"]="error: entry could not be created"; // ???
$lang["glossar_update_erfolgreich"]="entry updated successfully"; // ????
$lang["glossar_update_fehlgeschlagen"]="error: entry could not be updated"; // ???
$lang["glossar_delete_erfolgreich"]="entry deleted successfully"; // ????
$lang["glossar_delete_fehlgeschlagen"]="error: entry could not be deleted"; // ???
$lang["glossar_ja"]="yes";
$lang["glossar_nein"]="no";
$lang["glossar_neu_kurz"]="new";
$lang["glossar_loeschen_kurz"]="delete";
$lang["glossar_bearbeiten_kurz"]="edit";
$lang["glossar_id"]="ID";
$lang["glossar_user"]="user";
$lang["glossar_tpl_imgzo"]="image: top, centered";
$lang["glossar_tpl_imgzu"]="image: bottom, centered";
$lang["glossar_tpl_imgro"]="image: top, right";
$lang["glossar_tpl_imgru"]="image: bottom, right";
$lang["glossar_tpl_imgol"]="image: top, left";
$lang["glossar_tpl_imglu"]="image: bottom, left";
$lang["glossar_tpl_imgl"]="image: left";
$lang["glossar_tpl_imgr"]="image: right";
$lang["glossar_tpl_nurtext"]="text only";

?>