<?php
$lang["glossar_verwaltung"]="Glossarverwaltung";
$lang["glossar_neu"]="Neuen Glossareintrag anlegen";
$lang["glossar_titel"]="Titel";
$lang["glossar_text"]="Text";
$lang["glossar_bild"]="Bild";
$lang["glossar_tpl"]="Template";
$lang["glossar_anlegen"]="Glossareintrag anlegen";
$lang["glossar_bearbeiten"]="Glossareintrag bearbeiten";
$lang["glossar_speichern"]="speichern";
$lang["glossar_counter"]="Zähler";
$lang["glossar_loeschen"]="Glossareintrag löschen";
$lang["glossar_notfound"]="Fehler: Glossareintrag nicht gefunden";
$lang["glossar_insert_erfolgreich"]="Artikel erfolgreich eingefügt"; // ????
$lang["glossar_insert_fehlgeschlagen"]="Fehler: Artikel konnte nicht eingefügt werden"; // ???
$lang["glossar_update_erfolgreich"]="Artikel erfolgreich geändert"; // ????
$lang["glossar_update_fehlgeschlagen"]="Fehler: Artikel konnte nicht geändert werden"; // ???
$lang["glossar_delete_erfolgreich"]="Artikel erfolgreich gelöscht"; // ????
$lang["glossar_delete_fehlgeschlagen"]="Fehler: Artikel konnte nicht gelöscht werden"; // ???
$lang["glossar_ja"]="ja";
$lang["glossar_nein"]="nein";
$lang["glossar_neu_kurz"]="neu";
$lang["glossar_loeschen_kurz"]="löschen";
$lang["glossar_bearbeiten_kurz"]="bearbeiten";
$lang["glossar_id"]="ID";
$lang["glossar_user"]="user";
$lang["glossar_tpl_imgzo"]="Bild oben zentriert";
$lang["glossar_tpl_imgzu"]="Bild unten zentriert";
$lang["glossar_tpl_imgro"]="Bild rechts oben";
$lang["glossar_tpl_imgru"]="Bild rechts unten";
$lang["glossar_tpl_imgol"]="Bild links oben";
$lang["glossar_tpl_imglu"]="Bild links unten";
$lang["glossar_tpl_imgl"]="Bild links";
$lang["glossar_tpl_imgr"]="Bild rechts";
$lang["glossar_tpl_nurtext"]="nur Text";

?>