<?php
$lang["groups_verwaltung"]="groups and users";
$lang["groups_name"]="group name";
$lang["groups_bearbeiten"]="edit group";
$lang["groups_anlegen"]="create group";
$lang["groups_zugriff"]="access";
$lang["groups_erstellen"]="create";
$lang["groups_aendern"]="edit";
$lang["groups_loeschen"]="delete";
$lang["groups_modul"]="module";
$lang["groups_speichern"]="save";
$lang["groups_insert_erfolgreich"]="group created successfully"; // ????
$lang["groups_insert_fehlgeschlagen"]="error: group could not be created"; // ???
$lang["groups_update_erfolgreich"]="group updated successfully"; // ????
$lang["groups_update_fehlgeschlagen"]="error: group could not be updated"; // ???
$lang["groups_delete_erfolgreich"]="group deleted successfully"; // ????
$lang["groups_delete_fehlgeschlagen"]="error: group could not be deleted"; // ???

?>