<?php
$lang["groups_verwaltung"]="Gruppen- und Rechteverwaltung";
$lang["groups_name"]="Gruppenname";
$lang["groups_bearbeiten"]="Gruppe bearbeiten";
$lang["groups_anlegen"]="Gruppe anlegen";
$lang["groups_zugriff"]="Zugriff";
$lang["groups_erstellen"]="Erstellen";
$lang["groups_zugriff"]="Zugriff";
$lang["groups_aendern"]="Ändern";
$lang["groups_loeschen"]="Löschen";
$lang["groups_modul"]="Modul";
$lang["groups_speichern"]="speichern";
$lang["groups_insert_erfolgreich"]="Gruppe erfolgreich eingefügt"; // ????
$lang["groups_insert_fehlgeschlagen"]="Fehler: Gruppe konnte nicht eingefügt werden"; // ???
$lang["groups_update_erfolgreich"]="Gruppe erfolgreich geändert"; // ????
$lang["groups_update_fehlgeschlagen"]="Fehler: Gruppe konnte nicht geändert werden"; // ???
$lang["groups_delete_erfolgreich"]="Gruppe erfolgreich gelöscht"; // ????
$lang["groups_delete_fehlgeschlagen"]="Fehler: Gruppe konnte nicht gelöscht werden"; // ???

?>