<?php
$lang["groups_verwaltung"]="Gruppen- und Rechteverwaltung";
$lang["groups_name"]="Gruppenname";
$lang["groups_bearbeiten"]="Gruppe bearbeiten";
$lang["groups_anlegen"]="Gruppe anlegen";
$lang["groups_zugriff"]="Zugriff";
$lang["groups_erstellen"]="Erstellen";
$lang["groups_zugriff"]="Zugriff";
$lang["groups_aendern"]="&Auml;ndern";
$lang["groups_loeschen"]="L&ouml;schen";
$lang["groups_modul"]="Modul";
$lang["groups_speichern"]="speichern";
$lang["groups_insert_erfolgreich"]="Gruppe erfolgreich eingef&uuml;gt"; // ????
$lang["groups_insert_fehlgeschlagen"]="Fehler: Gruppe konnte nicht eingef&uuml;gt werden"; // ???
$lang["groups_update_erfolgreich"]="Gruppe erfolgreich ge&auml;ndert"; // ????
$lang["groups_update_fehlgeschlagen"]="Fehler: Gruppe konnte nicht ge&auml;ndert werden"; // ???
$lang["groups_delete_erfolgreich"]="Gruppe erfolgreich gel&ouml;scht"; // ????
$lang["groups_delete_fehlgeschlagen"]="Fehler: Gruppe konnte nicht gel&ouml;scht werden"; // ???
?>