<?php
$lang["messages_verwaltung"]="Nachrichten";
$lang["messages_neu"]="neu";
$lang["messages_topic"]="Betreff";
$lang["messages_status"]="Status";
$lang["messages_answer"]="antworten";
$lang["messages_anwsertopic"]="antw:";
$lang["messages_anwsermsg"]="--------";
$lang["messages_bearbeiten"]="bearbeiten";
$lang["messages_loeschen"]="l&ouml;schen";
$lang["messages_status_neu"]="neu";
$lang["messages_created"]="Datum";
$lang["messages_fuser"]="von";
$lang["messages_tuser"]="an";
$lang["messages_status_inbearb"]="in Bearbeitung";
$lang["messages_status_abgeschl"]="erledigt";
$lang["messages_status_gesendet"]="gesendet";
$lang["messages_speichern"]="speichern";
$lang["messages_notfound"]="Nachricht nicht gefunden";
$lang["messages_tuser_fehlt"]="Fehler: Empf&auml;nger fehlt";
$lang["messages_topic_fehlt"]="Fehler: Betreff fehlt";
$lang["messages_text_fehlt"]="Fehler: Nachrichtentext fehlt";
$lang["messages_insert_erfolgreich"]="Nachricht erfolgreich eingef&uuml;gt"; // ????
$lang["messages_insert_fehlgeschlagen"]="Fehler: Nachricht konnte nicht eingef&uuml;gt werden"; // ???
$lang["messages_update_erfolgreich"]="Nachricht erfolgreich ge&auml;ndert"; // ????
$lang["messages_update_fehlgeschlagen"]="Fehler: Nachricht konnte nicht ge&auml;ndert werden"; // ???
?>