<?php
$lang["messages_verwaltung"]="Nachrichten";
$lang["messages_neu"]="neu";
$lang["messages_bearbeiten"]="bearbeiten";
$lang["messages_loeschen"]="löschen";
$lang["messages_status_neu"]="neu";
$lang["messages_status_inbearb"]="in bearbeitung";
$lang["messages_status_abgeschl"]="abgeschlossen";
$lang["messages_insert_erfolgreich"]="Nachricht erfolgreich eingefügt"; // ????
$lang["messages_insert_fehlgeschlagen"]="Nachricht konnte nicht eingefügt werden"; // ???
$lang["messages_update_erfolgreich"]="Nachricht erfolgreich geändert"; // ????
$lang["messages_update_fehlgeschlagen"]="Nachricht konnte nicht geändert werden"; // ???
?>