<?php
$lang["messages_verwaltung"]="messages";
$lang["messages_neu"]="create message";
$lang["messages_topic"]="subject";
$lang["messages_bearbeiten"]="edit";
$lang["messages_loeschen"]="delete";
$lang["messages_status_neu"]="new";
$lang["messages_created"]="created";
$lang["messages_fuser"]="to";
$lang["messages_tuser"]="from";
$lang["messages_status_inbearb"]="being edited";
$lang["messages_status_abgeschl"]="done";
$lang["messages_speichern"]="save";
$lang["messages_notfound"]="error: message not found";
$lang["messages_tuser_fehlt"]="error: no recipient";
$lang["messages_topic_fehlt"]="error: no subject";
$lang["messages_text_fehlt"]="error: no message text";
$lang["messages_insert_erfolgreich"]="message created successfully"; // ????
$lang["messages_insert_fehlgeschlagen"]="error: message could not be created"; // ???
$lang["messages_update_erfolgreich"]="message updated successfully"; // ????
$lang["messages_update_fehlgeschlagen"]="error: message could not be updated"; // ???
?>