<?php
$lang["messages_verwaltung"]="Nachrichten";
$lang["messages_neu"]="neu";
$lang["messages_topic"]="Betreff";
$lang["messages_bearbeiten"]="bearbeiten";
$lang["messages_loeschen"]="löschen";
$lang["messages_status_neu"]="neu";
$lang["messages_created"]="Datum";
$lang["messages_fuser"]="von";
$lang["messages_tuser"]="an";
$lang["messages_status_inbearb"]="in Bearbeitung";
$lang["messages_status_abgeschl"]="erledigt";
$lang["messages_speichern"]="speichern";
$lang["messages_notfound"]="Nachricht nicht gefunden";
$lang["messages_tuser_fehlt"]="Fehler: Empfänger fehlt";
$lang["messages_topic_fehlt"]="Fehler: Betreff fehlt";
$lang["messages_text_fehlt"]="Fehler: Nachrichtentext fehlt";
$lang["messages_insert_erfolgreich"]="Nachricht erfolgreich eingefügt"; // ????
$lang["messages_insert_fehlgeschlagen"]="Fehler: Nachricht konnte nicht eingefügt werden"; // ???
$lang["messages_update_erfolgreich"]="Nachricht erfolgreich geändert"; // ????
$lang["messages_update_fehlgeschlagen"]="Fehler: Nachricht konnte nicht geändert werden"; // ???
?>