<?php
$lang["navigation_verwaltung"]="navigation";
$lang["navigation_name"]="name";
$lang["navigation_typ"]="type";
$lang["navigation_eintrag"]="entry";
$lang["navigation_bearbeiten"]="edit navigation";
$lang["navigation_anlegen"]="create navigation";
$lang["navigation_zugriff"]="access";
$lang["navigation_speichern"]="save";
$lang["navigation_inaktiv"]="inactive";
$lang["navigation_anfang"]="at the top";
$lang["navigation_ende"]="at the bottom";
$lang["navigation_insert_erfolgreich"]="navigation created successfully"; // ????
$lang["navigation_insert_fehlgeschlagen"]="error: navigation could not be created"; // ???
$lang["navigation_update_erfolgreich"]="navigation updated successfully"; // ????
$lang["navigation_update_fehlgeschlagen"]="error: navigation could not be updated"; // ???
$lang["navigation_delete_erfolgreich"]="navigation deleted successfully"; // ????
$lang["navigation_delete_fehlgeschlagen"]="error: navigation could not be deleted"; // ???

$lang["navigation_move_up_erfolgreich"]="navigation moved to the top successfully"; // ????
$lang["navigation_move_up_fehlgeschlagen"]="error: navigation could not be moved to the top"; // ???

$lang["navigation_move_down_erfolgreich"]="navigation moved to the bottom successfully"; // ????
$lang["navigation_move_down_fehlgeschlagen"]="error: navigation could not be moved to the bottom"; // ???

?>