<?php
$lang["navigation_verwaltung"]="Navigation";
$lang["navigation_name"]="Name";
$lang["navigation_typ"]="Typ";
$lang["navigation_eintrag"]="Eintrag";
$lang["navigation_bearbeiten"]="Navigation bearbeiten";
$lang["navigation_anlegen"]="Navigation anlegen";
$lang["navigation_zugriff"]="Zugriff";
$lang["navigation_speichern"]="speichern";
$lang["navigation_inaktiv"]="Inaktiv";
$lang["navigation_anfang"]="am Anfang";
$lang["navigation_ende"]="am Ende";
$lang["navigation_insert_erfolgreich"]="Navigation erfolgreich eingef&uuml;gt"; // ????
$lang["navigation_insert_fehlgeschlagen"]="Fehler: Navigation konnte nicht eingef&uuml;gt werden"; // ???
$lang["navigation_update_erfolgreich"]="Navigation erfolgreich ge&auml;ndert"; // ????
$lang["navigation_update_fehlgeschlagen"]="Fehler: Navigation konnte nicht ge&auml;ndert werden"; // ???
$lang["navigation_delete_erfolgreich"]="Navigation erfolgreich gel&ouml;scht"; // ????
$lang["navigation_delete_fehlgeschlagen"]="Fehler: Navigation konnte nicht gel&ouml;scht werden"; // ???

$lang["navigation_move_up_erfolgreich"]="Navigation erfolgreich nach oben verschoben"; // ????
$lang["navigation_move_up_fehlgeschlagen"]="Fehler: Navigation konnte nicht nach oben verschoben werden"; // ???

$lang["navigation_move_down_erfolgreich"]="Navigation erfolgreich nach unten verschoben"; // ????
$lang["navigation_move_down_fehlgeschlagen"]="Fehler: Navigation konnte nicht nach unten verschoben werden"; // ???

?>