<?php
$lang["news_verwaltung"]="News und Titelthema";
$lang["news_bearbeiten"]="News-Eintrag bearbeiten";
$lang["news_anlegen"]="News-Eintrag anlegen";
$lang["news_speichern"]="speichern";
$lang["news_name"]="Name";
$lang["news_artikel"]="Artikel";
$lang["news_seite"]="Seite";
$lang["news_artikel_anz"]="Anzahl Artikel";
$lang["news_insert_erfolgreich"]="Newseintrag erfolgreich eingefügt"; // ????
$lang["news_insert_fehlgeschlagen"]="Fehler: Newseintrag konnte nicht eingefügt werden"; // ???
$lang["news_update1_erfolgreich"]="Altes Topthema erfolgreich entfernt"; // ????
$lang["news_update1_fehlgeschlagen"]="Fehler: Altes Topthema konnte nicht entfernt werden"; // ???
$lang["news_update2_erfolgreich"]="Neues Topthema erfolgreich eingetragen"; // ????
$lang["news_update2_fehlgeschlagen"]="Fehler: Neues Topthema konnte nicht eingetragen werden"; // ???
$lang["news_update3_erfolgreich"]="Newseintrag erfolgreich geändert"; // ????
$lang["news_update3_fehlgeschlagen"]="Fehler: Newseintrag konnte nicht geändert werden"; // ???
$lang["news_delete_erfolgreich"]="Newseintrag erfolgreich gelöscht"; // ????
$lang["news_delete_fehlgeschlagen"]="Fehler: Newseintrag konnte nicht gelöscht werden"; // ???
$lang["news_moveup_erfolgreich"]="Newseintrag erfolgreich nach oben verschoben "; // ????
$lang["news_moveup_fehlgeschlagen"]="Fehler: Newseintrag konnte nicht nach oben verschoben werden"; // ???
$lang["news_movedown_erfolgreich"]="Newseintrag erfolgreich nach unten verschoben"; // ????
$lang["news_movedown_fehlgeschlagen"]="Fehler: Newseintrag konnte nicht nach unten verschoben werden"; // ???

?>