<?php
$lang["news_verwaltung"]="news and top story";
$lang["news_bearbeiten"]="edit news entry";
$lang["news_anlegen"]="create news entry";
$lang["news_speichern"]="save";
$lang["news_name"]="name";
$lang["news_artikel"]="article";
$lang["news_seite"]="page";
$lang["news_artikel_anz"]="number of articles";
$lang["news_insert_erfolgreich"]="news entry created successfully"; // ????
$lang["news_insert_fehlgeschlagen"]="error: news entry could not be created"; // ???
$lang["news_update1_erfolgreich"]="old top story removed successfully"; // ????
$lang["news_update1_fehlgeschlagen"]="error: old top story could not be removed"; // ???
$lang["news_update2_erfolgreich"]="new top story created successfully"; // ????
$lang["news_update2_fehlgeschlagen"]="error: new top story could not be created"; // ???
$lang["news_update3_erfolgreich"]="news entry updated successfully"; // ????
$lang["news_update3_fehlgeschlagen"]="error: news entry could not be updated"; // ???
$lang["news_delete_erfolgreich"]="news entry deleted successfully"; // ????
$lang["news_delete_fehlgeschlagen"]="error: news entry could not be deleted"; // ???
$lang["news_moveup_erfolgreich"]="news entry moved to the top successfully"; // ????
$lang["news_moveup_fehlgeschlagen"]="error: news entry could not be moved to the top"; // ???
$lang["news_movedown_erfolgreich"]="news entry moved to the buttom successfully"; // ????
$lang["news_movedown_fehlgeschlagen"]="error: news entry could not be moved to the buttom"; // ???

?>