<?php
$lang["profile_verwaltung"]="profiles";
$lang["profile_aktiv"]="active";
$lang["profile_name"]="name";
$lang["profile_start"]="start page";
$lang["profile_404"]="page not found (error 404)";
$lang["profile_bild"]="profile icon";
$lang["profile_speichern"]="save";
$lang["profile_neu"]="create new profile";
$lang["profile_bearbeiten"]="edit profile";
$lang["profile_insert_fehlerhaft"]="error: profile could not be created";
$lang["profile_insert_erfolgreich"]="profile created successfully";
$lang["profile_update_fehlerhaft"]="error: profile could not be updated";
$lang["profile_update_erfolgreich"]="profile updated successfully";
$lang["profile_delete_fehlerhaft"]="error: profile could not be deleted";
$lang["profile_delete_erfolgreich"]="profile deleted successfully";
?>
