<?php
$lang["profile_verwaltung"]="Profile";
$lang["profile_aktiv"]="aktiv";
$lang["profile_name"]="name";
$lang["profile_start"]="Startseite";
$lang["profile_404"]="404";
$lang["profile_bild"]="Seitenlogo";
$lang["profile_speichern"]="speichern";
$lang["profile_neu"]="Neues Profil anlegen";
$lang["profile_bearbeiten"]="Profil bearbeiten";
$lang["profile_insert_fehlerhaft"]="Profil einfügen fehlgeschlagen";
$lang["profile_insert_erfolgreich"]="Profil einfügen erfolgreich";
$lang["profile_update_fehlerhaft"]="Profil bearbeiten fehlgeschlagen";
$lang["profile_update_erfolgreich"]="Profil bearbeiten erfolgreich";
$lang["profile_delete_fehlerhaft"]="Profil löschen fehlgeschlagen";
$lang["profile_delete_erfolgreich"]="Profil löschen erfolgreich";
?>
