<?php
$lang["profile_verwaltung"]="Profile";
$lang["profile_aktiv"]="aktiv";
$lang["profile_name"]="Name";
$lang["profile_start"]="Startseite";
$lang["profile_404"]="Seite nicht gefunde (Fehler 404)";
$lang["profile_bild"]="Seitenlogo";
$lang["profile_speichern"]="speichern";
$lang["profile_neu"]="Neues Profil anlegen";
$lang["profile_bearbeiten"]="Profil bearbeiten";
$lang["profile_insert_fehlerhaft"]="Fehler: Profil einfügen fehlgeschlagen";
$lang["profile_insert_erfolgreich"]="Profil einfügen erfolgreich";
$lang["profile_update_fehlerhaft"]="Fehler: Profil bearbeiten fehlgeschlagen";
$lang["profile_update_erfolgreich"]="Profil bearbeiten erfolgreich";
$lang["profile_delete_fehlerhaft"]="Fehler: Profil löschen fehlgeschlagen";
$lang["profile_delete_erfolgreich"]="Profil löschen erfolgreich";
?>
