<?php
$lang["rights_verwaltung"]="rights management";
$lang["rights_groupname"]="groupname";
$lang["rights_username"]="authorname";
$lang["rights_newacl"]="new";
$lang["rights_newaclinsert"]="isnsert";
$lang["rights_erstellen"]="create";
$lang["rights_aendern"]="modify";
$lang["rights_loeschen"]="delete";
$lang["rights_rechte"]="rights";
$lang["rights_modul"]="modul";
$lang["rights_acl_delete"]="delete entry";
$lang["rights_speichern"]="save";
$lang["rights_zurueck"]="back";
$lang["rights_insert_erfolgreich"]="right created successfully"; // ????
$lang["rights_insert_fehlgeschlagen"]="error: right could not be created"; // ???
$lang["rights_update_erfolgreich"]="right updated successsfully"; // ????
$lang["rights_update_fehlgeschlagen"]="error: right could not be updated"; // ???
$lang["rights_delete_erfolgreich"]="right deleted successfully"; // ????
$lang["rights_delete_fehlgeschlagen"]="error: right could not be deleted"; // ???
?>