<?php
$lang["rights_verwaltung"]="Rechteverwaltung";
$lang["rights_groupname"]="Gruppenname";
$lang["rights_username"]="Autorname";
$lang["rights_newacl"]="Neu";
$lang["rights_newaclinsert"]="einfügen";
$lang["rights_erstellen"]="Erstellen";
$lang["rights_aendern"]="Ändern";
$lang["rights_loeschen"]="Löschen";
$lang["rights_rechte"]="Rechte";
$lang["rights_modul"]="Modul";
$lang["rights_acl_delete"]="Eintrag löschen";
$lang["rights_speichern"]="speichern";
$lang["rights_zurueck"]="zurück";
$lang["rights_insert_erfolgreich"]="<p>Rechte erfolgreich eingefügt</p>"; // ????
$lang["rights_insert_fehlgeschlagen"]="<p>Fehler: Rechte konnte nicht eingefügt werden</p>"; // ???
$lang["rights_update_erfolgreich"]="<p>Rechte erfolgreich geändert</p>"; // ????
$lang["rights_update_fehlgeschlagen"]="<p>Fehler: Rechte konnte nicht geändert werden</p>"; // ???
$lang["rights_delete_erfolgreich"]="<p>Rechte erfolgreich gelöscht</p>"; // ????
$lang["rights_delete_fehlgeschlagen"]="<p>Fehler: Rechte konnte nicht gelöscht werden</p>"; // ???

?>