<?php
$lang["rights_verwaltung"]="Rechteverwaltung";
$lang["rights_groupname"]="Gruppenname";
$lang["rights_username"]="Autorname";
$lang["rights_newacl"]="Neu";
$lang["rights_newaclinsert"]="einf&uuml;gen";
$lang["rights_erstellen"]="Erstellen";
$lang["rights_aendern"]="&Auml;ndern";
$lang["rights_loeschen"]="L&ouml;schen";
$lang["rights_rechte"]="Rechte";
$lang["rights_modul"]="Modul";
$lang["rights_acl_delete"]="Eintrag l&ouml;schen";
$lang["rights_speichern"]="speichern";
$lang["rights_zurueck"]="zur&uuml;ck";
$lang["rights_insert_erfolgreich"]="<p>Rechte erfolgreich eingef&uuml;gt</p>"; // ????
$lang["rights_insert_fehlgeschlagen"]="<p>Fehler: Rechte konnte nicht eingef&uuml;gt werden</p>"; // ???
$lang["rights_update_erfolgreich"]="<p>Rechte erfolgreich ge&auml;ndert</p>"; // ????
$lang["rights_update_fehlgeschlagen"]="<p>Fehler: Rechte konnte nicht ge&auml;ndert werden</p>"; // ???
$lang["rights_delete_erfolgreich"]="<p>Rechte erfolgreich gel&ouml;scht</p>"; // ????
$lang["rights_delete_fehlgeschlagen"]="<p>Fehler: Rechte konnte nicht gel&ouml;scht werden</p>"; // ???

?>