<?php
$lang["sitemap_verwaltung"]="sitemaps";
$lang["sitemap_titel"]="name";
$lang["sitemap_counter"]="counter";
$lang["sitemap_nav"]="navigation";
$lang["sitemap_anlegen"]="create sitemap";
$lang["sitemap_bearbeiten"]="edit sitemap";
$lang["sitemap_logo_klein"]="small icon";
$lang["sitemap_logo_gross"]="large icon";
$lang["sitemap_speichern"]="save";
$lang["sitemap_insert_erfolgreich"]="sitemap created successfully"; // ????
$lang["sitemap_insert_fehlgeschlagen"]="error: sitemap could not be created"; // ???
$lang["sitemap_update_erfolgreich"]="sitemap updated successfully"; // ????
$lang["sitemap_update_fehlgeschlagen"]="error: sitemap could not be updated"; // ???
$lang["sitemap_delete_erfolgreich"]="sitemap deleted successfully"; // ????
$lang["sitemap_delete_fehlgeschlagen"]="error: sitemap could not be deleted"; // ???
?>