<?php
$lang["user_verwaltung"]="User";
$lang["user_neu"]="Neuen User anlegen";
$lang["user_bearbeiten"]="User bearbeiten";
$lang["user_name"]="Name";
$lang["user_gruppe"]="Gruppe";
$lang["user_activ"]="aktiv";
$lang["user_self"]="-----";
$lang["user_pass"]="Passwort";
$lang["user_speichern"]="speichern";
$lang["user_insert_erfolgreich"]="user created successfully";
$lang["user_insert_fehlgeschlagen"]="error: user could not be created"; 
$lang["user_update_erfolgreich"]="user updated succesfully";
$lang["user_update_fehlgeschlagen"]="error: user could not be updated";
$lang["user_delete_erfolgreich"]="user deleted succesfully";
$lang["user_delete_fehlgeschlagen"]="error: user could not be deleted";
?>