<?php
$lang["user_verwaltung"]="users";
$lang["user_neu"]="create new user";
$lang["user_bearbeiten"]="edit user";
$lang["user_name"]="name";
$lang["user_gruppe"]="group";
$lang["user_activ"]="active";
$lang["user_self"]="-----";
$lang["user_pass"]="password";
$lang["user_speichern"]="save";
$lang["user_insert_erfolgreich"]="user created successfully";
$lang["user_insert_fehlgeschlagen"]="error: user could not be created"; 
$lang["user_update_erfolgreich"]="user updated succesfully";
$lang["user_update_fehlgeschlagen"]="error: user could not be updated";
$lang["user_delete_erfolgreich"]="user deleted succesfully";
$lang["user_delete_fehlgeschlagen"]="error: user could not be deleted";
?>