<?php
$lang["user_verwaltung"]="Benutzer";
$lang["user_neu"]="Neuen Benutzer anlegen";
$lang["user_bearbeiten"]="Benutzer bearbeiten";
$lang["user_name"]="Name";
$lang["user_gruppe"]="Gruppe";
$lang["user_activ"]="aktiv";
$lang["user_self"]="-----";
$lang["user_pass"]="Passwort";
$lang["user_speichern"]="speichern";
$lang["user_insert_erfolgreich"]="Benutzer erfolgreich angelegt";
$lang["user_insert_fehlgeschlagen"]="Fehler: Benutzer konnte nicht angelegt werden"; 
$lang["user_update_erfolgreich"]="Benutzer erfolgreich aktualisiert";
$lang["user_update_fehlgeschlagen"]="Fehler: Benutzer konnte nicht aktualisiert werden";
$lang["user_delete_erfolgreich"]="Benutzer erfolgreich gelöscht";
$lang["user_delete_fehlgeschlagen"]="Fehler: Benutzer konnte nicht gelöscht werden";
?>